# Generated by Django 4.2.19 on 2025-02-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naileditapi', '0002_alter_material_description_alter_tool_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='materials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
