# Generated by Django 4.2.19 on 2025-03-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naileditapi', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
