# Generated by Django 4.2.19 on 2025-03-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naileditapi', '0005_alter_project_date_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='uid',
            field=models.CharField(default='default_uid', max_length=30),
        ),
    ]
